### ISSUE TITLE
rasa evaluate markers all --config markers.yml extracted_markers.csv >> Erroring out

### ISSUE THREAD

**Issue by pksvv** [rctatman/Rasa-3.0-rock-paper-scissors-chatbot#1]
Hi Rachael - I am facing this issue while running the evaluate marker. I've setup redis tracker and conversation is happening smoothly.

**_Chatlog_**

```
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  hi                                                                                                              
Type Rock, Paper, or Scissors to play.
Your input ->  rockl                                                                                                           
You chose rockl
The computer chose scissors
It was a tie !!
Do you want to play again?
Your input ->  rock                                                                                                            
You chose rock
The computer chose paper
The computer won this round.
Do you want to play again?
Your input ->  paper                                                                                                           
You chose paper
The computer chose paper
It was a tie !!
Do you want to play again?
Your input ->                               
```

![image](https://user-images.githubusercontent.com/8981899/144763361-e913bb8f-38bd-470e-b7a2-ea8716d361fa.png)

Chat key in Redis

`{"events": [{"event": "action", "timestamp": 1638735160.470829, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "action_session_start", "policy": null, "confidence": 1.0, "action_text": null, "hide_rule_turn": false}, {"event": "session_started", "timestamp": 1638735160.471524, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}}, {"event": "action", "timestamp": 1638735160.4715579, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "action_listen", "policy": null, "confidence": null, "action_text": null, "hide_rule_turn": false}, {"event": "user", "timestamp": 1638735160.540569, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "hi", "parse_data": {"intent": {"name": "greet", "confidence": 0.9999997615814209}, "entities": [], "text": "hi", "message_id": "dc40c8e7e8694b3b91583af911db0a41", "metadata": {}, "text_tokens": [[0, 2]], "intent_ranking": [{"name": "greet", "confidence": 0.9999997615814209}, {"name": "bot_challenge", "confidence": 1.0229746294498909e-07}, {"name": "affirm", "confidence": 6.382774841995342e-08}, {"name": "goodbye", "confidence": 2.0069968797997717e-08}, {"name": "inform", "confidence": 3.3100751029024877e-09}, {"name": "deny", "confidence": 2.9777285082133176e-09}], "response_selector": {"all_retrieval_intents": [], "default": {"response": {"responses": null, "confidence": 0.0, "intent_response_key": null, "utter_action": "utter_None"}, "ranking": []}}}, "input_channel": "cmdline", "message_id": "dc40c8e7e8694b3b91583af911db0a41"}, {"event": "user_featurization", "timestamp": 1638735160.605073, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "use_text_for_featurization": false}, {"event": "action", "timestamp": 1638735160.605084, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "utter_play", "policy": "MemoizationPolicy", "confidence": 1.0, "action_text": null, "hide_rule_turn": false}, {"event": "bot", "timestamp": 1638735160.605115, "metadata": {"utter_action": "utter_play", "model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "Type Rock, Paper, or Scissors to play.", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}, {"event": "action", "timestamp": 1638735160.636412, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "action_listen", "policy": "MemoizationPolicy", "confidence": 1.0, "action_text": null, "hide_rule_turn": false}, {"event": "user", "timestamp": 1638735425.792852, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "rock", "parse_data": {"intent": {"name": "inform", "confidence": 0.999994158744812}, "entities": [{"entity": "choice", "start": 0, "end": 4, "confidence_entity": 0.9991344809532166, "value": "rock", "extractor": "DIETClassifier"}], "text": "rock", "message_id": "d8163048385a40388a07152932cc84c4", "metadata": {}, "text_tokens": [[0, 4]], "intent_ranking": [{"name": "inform", "confidence": 0.999994158744812}, {"name": "goodbye", "confidence": 2.125264700225671e-06}, {"name": "deny", "confidence": 1.3575140656030271e-06}, {"name": "bot_challenge", "confidence": 1.1628931133600418e-06}, {"name": "affirm", "confidence": 1.0578573892416898e-06}, {"name": "greet", "confidence": 1.0340110634388111e-07}], "response_selector": {"all_retrieval_intents": [], "default": {"response": {"responses": null, "confidence": 0.0, "intent_response_key": null, "utter_action": "utter_None"}, "ranking": []}}}, "input_channel": "cmdline", "message_id": "d8163048385a40388a07152932cc84c4"}, {"event": "slot", "timestamp": 1638735425.793377, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "choice", "value": "rock"}, {"event": "user_featurization", "timestamp": 1638735425.8639889, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "use_text_for_featurization": false}, {"event": "action", "timestamp": 1638735425.8640141, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "action_play_rps", "policy": "TEDPolicy", "confidence": 0.5698628425598145, "action_text": null, "hide_rule_turn": false}, {"event": "bot", "timestamp": 1638735425.864065, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "You chose rock", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}, {"event": "bot", "timestamp": 1638735425.864068, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "The computer chose scissors", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}, {"event": "bot", "timestamp": 1638735425.8640692, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "Congrats ! You won.", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}, {"event": "action", "timestamp": 1638735425.892309, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "utter_play_again", "policy": "TEDPolicy", "confidence": 0.9060202836990356, "action_text": null, "hide_rule_turn": false}, {"event": "bot", "timestamp": 1638735425.892341, "metadata": {"utter_action": "utter_play_again", "model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "text": "Do you want to play again?", "data": {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}}, {"event": "action", "timestamp": 1638735425.920325, "metadata": {"model_id": "24b46c1fcdb8452fb8b309b0c5b89ec7"}, "name": "action_listen", "policy": "TEDPolicy", "confidence": 0.9901753067970276, "action_text": null, "hide_rule_turn": false}], "name": "4a065d7953d146c593a91496b7f1a7f0"}`

`(rasa-latest) vipul:rasa3x$ rasa evaluate markers all --config markers.yml extracted_markers.csv
`
_Traceback (most recent call last):
File "/opt/anaconda3/envs/rasa-latest/bin/rasa", line 8, in
sys.exit(main())
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/main.py", line 121, in main
cmdline_arguments.func(cmdline_arguments)
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/cli/evaluate.py", line 94, in _run_markers_cli
_run_markers(
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/cli/evaluate.py", line 177, in run_markers
markers.evaluate_trackers(
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/evaluation/marker_base.py", line 619, in evaluate_trackers
for tracker in trackers:
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/evaluation/marker_tracker_loader.py", line 103, in load
yield self.tracker_store.retrieve_full_tracker(sender)
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/tracker_store.py", line 219, in retrieve_full_tracker
return self.retrieve(conversation_id)
File "/opt/anaconda3/envs/rasa-latest/lib/python3.8/site-packages/rasa/core/tracker_store.py", line 368, in retrieve
stored = self.red.get(self.key_prefix + sender_id)
TypeError: can only concatenate str (not "bytes") to str

**Comment by pksvv** [comment]
https://github.com/pksvv/rasa3.0/issues/4
